### ISSUE TITLE
BetterString v11.33 crashes YAM

### ISSUE THREAD

**Issue by alpyre** [amiga-mui/betterstring#5]
BetterString v11.33 crashes YAM with error code #80000005 on my Amiga:
Specs:
68060+BVision Amiga1200
RAM: 256MB Fast
OS: AmigaOS 3.9 + Boing Bag 2
YAM version: 2.10-dev (it crashes other versions as well)

I could not reproduce the crash on WinUAE/FS-UAE.

Downgrading to BetterString v11.29 solves the issue.

**Comment by tboeckel** [comment]
Do you have some more valuable information than "it crashes"? Ok, it seems to be a "division by zero" error, but some more details would be nice.
There have been more releases between 11.29 and 11.33. What about these? Just to isolate the issue to a specific release. There haven't been too many changes in each individual release, so it should be quite easy to track this issue down.
There latest changes were about alpha transparency. Are you using a colormapped or truecolor screen?

**Comment by alpyre** [comment]
I tested it with 11.32 now. And it works. The problem must be about the changes between 11.32  and 11.33.

It seems like it crashes at the stage it prints the "Filter list..." text inside the BetterString gadget for the list filter top left.
![YAMcrash](https://user-images.githubusercontent.com/19547271/66649823-cab92b00-ec37-11e9-99fb-adae74d362e5.gif)

**Comment by tboeckel** [comment]
[bstring_11.34.zip](https://github.com/amiga-mui/betterstring/files/3717425/bstring_11.34.zip)
This is an OS3 build with a possibly fixed division by zero. Please try it.

**Comment by alpyre** [comment]
Wow! So fast. Thanks. This one works. But now there is no "Filter list..." text inside the gadget.

**Comment by tboeckel** [comment]
I think I'll have to try to reproduce this issue myself. Fixing the division by zero was done without testing the actual result.

**Comment by alpyre** [comment]
I'm using a 16bit RTG screen (BVision) btw.

**Comment by tboeckel** [comment]
Please test this new version. For me it works correctly.
[bstring_11.34_2.zip](https://github.com/amiga-mui/betterstring/files/3720991/bstring_11.34_2.zip)

**Comment by alpyre** [comment]
bstring_11.34_2.zip doesn't crash, yet the InactiveContents text "Filter list..." still doesn't show up.

**Comment by tboeckel** [comment]
Crap! I think I forgot to update the working copy on the build server before I built the version for you. Please try this one.
[bstring_11.34_3.zip](https://github.com/amiga-mui/betterstring/files/3729716/bstring_11.34_3.zip)

**Comment by alpyre** [comment]
Thanks, but still the same. InactiveContents is still not visible.

**Comment by tboeckel** [comment]
Which version of cybergraphics.library do you have on your system?

**Comment by alpyre** [comment]
41.3

**Comment by tboeckel** [comment]
Ok. That must be the reason. WritePixelArrayAlpha() requires cybergraphics V45+

This version uses a custom WPAA implementation with a fallback to the real function in case it is available.
[bstring_11.34_4.zip](https://github.com/amiga-mui/betterstring/files/3731048/bstring_11.34_4.zip)

**Comment by alpyre** [comment]
This one works. The text is in a fainter color, which is great. It's not in italics though. InactiveContents used to be in italics, if the change is intended, this version is ok. Thanks for your time.

**Comment by tboeckel** [comment]
Yes, that is intended. Italic style is used on colormapped screens only. On truecolor screens the text is displayed with 50% transparency now. One text effect (italic style vs. transparency) should be enough.
